
# .github/workflows/multi-stage.yml

name: Multi-Stage

on:
  push:
    branches: ['none']
  pull_request:
    branches: ['none']
jobs:
  Linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm install
      - run: npm run linter
  Step-2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo This is stage 2
